// Auto-generated by pydantic2ts - DO NOT EDIT MANUALLY
// Run: pydantic2ts --module server/models --output web/src/types/generated.ts

// ============ Config Models ============

export interface EmbeddingConfig {
  provider: 'openai' | 'voyage' | 'local';
  model: string;
  dimensions: number;
  batch_size: number;
}

export interface VectorSearchConfig {
  enabled: boolean;
  top_k: number;
  similarity_threshold: number;
}

export interface SparseSearchConfig {
  enabled: boolean;
  top_k: number;
  bm25_k1: number;
  bm25_b: number;
}

export interface GraphSearchConfig {
  enabled: boolean;
  max_hops: number;
  top_k: number;
  include_communities: boolean;
}

export interface FusionConfig {
  method: 'rrf' | 'weighted';
  vector_weight: number;
  sparse_weight: number;
  graph_weight: number;
  rrf_k: number;
}

export interface RerankerConfig {
  mode: 'none' | 'local' | 'trained' | 'api';
  local_model: string | null;
  trained_model_path: string | null;
  api_provider: 'cohere' | 'voyage' | 'jina' | null;
  api_model: string | null;
  top_n: number;
  batch_size: number;
  max_length: number;
}

export interface ChunkerConfig {
  strategy: 'ast' | 'semantic' | 'fixed';
  chunk_size: number;
  chunk_overlap: number;
  min_chunk_size: number;
}

export interface ObservabilityConfig {
  metrics_enabled: boolean;
  tracing_enabled: boolean;
  grafana_url: string | null;
}

export interface TriBridConfig {
  embedding: EmbeddingConfig;
  vector_search: VectorSearchConfig;
  sparse_search: SparseSearchConfig;
  graph_search: GraphSearchConfig;
  fusion: FusionConfig;
  reranker: RerankerConfig;
  chunker: ChunkerConfig;
  observability: ObservabilityConfig;
}

// ============ Retrieval Models ============

export interface ChunkMatch {
  chunk_id: string;
  content: string;
  file_path: string;
  start_line: number;
  end_line: number;
  language: string | null;
  score: number;
  source: 'vector' | 'sparse' | 'graph';
  metadata: Record<string, unknown>;
}

export interface SearchRequest {
  query: string;
  repo_id: string;
  top_k: number;
  include_vector: boolean;
  include_sparse: boolean;
  include_graph: boolean;
}

export interface SearchResponse {
  query: string;
  matches: ChunkMatch[];
  fusion_method: string;
  reranker_mode: string;
  latency_ms: number;
  debug: Record<string, unknown> | null;
}

export interface AnswerRequest {
  query: string;
  repo_id: string;
  top_k: number;
  stream: boolean;
  system_prompt: string | null;
}

export interface AnswerResponse {
  query: string;
  answer: string;
  sources: ChunkMatch[];
  model: string;
  tokens_used: number;
  latency_ms: number;
}

// ============ Index Models ============

export interface Chunk {
  chunk_id: string;
  content: string;
  file_path: string;
  start_line: number;
  end_line: number;
  language: string | null;
  token_count: number;
  embedding: number[] | null;
  summary: string | null;
}

export interface IndexRequest {
  repo_id: string;
  repo_path: string;
  force_reindex: boolean;
}

export interface IndexStatus {
  repo_id: string;
  status: 'idle' | 'indexing' | 'complete' | 'error';
  progress: number;
  current_file: string | null;
  error: string | null;
  started_at: string | null;
  completed_at: string | null;
}

export interface IndexStats {
  repo_id: string;
  total_files: number;
  total_chunks: number;
  total_tokens: number;
  embedding_model: string;
  embedding_dimensions: number;
  last_indexed: string | null;
  file_breakdown: Record<string, number>;
}

// ============ Graph Models ============

export interface Entity {
  entity_id: string;
  name: string;
  entity_type: 'function' | 'class' | 'module' | 'variable' | 'concept';
  file_path: string | null;
  description: string | null;
  properties: Record<string, unknown>;
}

export interface Relationship {
  source_id: string;
  target_id: string;
  relation_type: 'calls' | 'imports' | 'inherits' | 'contains' | 'references' | 'related_to';
  weight: number;
  properties: Record<string, unknown>;
}

export interface Community {
  community_id: string;
  name: string;
  summary: string;
  member_ids: string[];
  level: number;
}

export interface GraphStats {
  repo_id: string;
  total_entities: number;
  total_relationships: number;
  total_communities: number;
  entity_breakdown: Record<string, number>;
  relationship_breakdown: Record<string, number>;
}

// ============ Eval Models ============

export interface DatasetEntry {
  entry_id: string;
  question: string;
  expected_chunks: string[];
  expected_answer: string | null;
  tags: string[];
  created_at: string;
}

export interface EvalRequest {
  repo_id: string;
  dataset_id: string | null;
  sample_size: number | null;
}

export interface EvalMetrics {
  mrr: number;
  recall_at_5: number;
  recall_at_10: number;
  recall_at_20: number;
  precision_at_5: number;
  ndcg_at_10: number;
  latency_p50_ms: number;
  latency_p95_ms: number;
}

export interface EvalResult {
  entry_id: string;
  question: string;
  retrieved_chunks: string[];
  expected_chunks: string[];
  reciprocal_rank: number;
  recall: number;
  latency_ms: number;
}

export interface EvalRun {
  run_id: string;
  repo_id: string;
  dataset_id: string;
  config_snapshot: TriBridConfig;
  metrics: EvalMetrics;
  results: EvalResult[];
  started_at: string;
  completed_at: string;
}

// ============ Chat Models ============

export interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
}

export interface ChatRequest {
  message: string;
  repo_id: string;
  conversation_id: string | null;
  stream: boolean;
}

export interface ChatResponse {
  conversation_id: string;
  message: Message;
  sources: ChunkMatch[];
  tokens_used: number;
}

// ============ Repo Models ============

export interface Repository {
  repo_id: string;
  name: string;
  path: string;
  description: string | null;
  created_at: string;
  last_indexed: string | null;
}

export interface RepoStats {
  repo_id: string;
  file_count: number;
  total_size_bytes: number;
  language_breakdown: Record<string, number>;
  index_stats: IndexStats | null;
  graph_stats: GraphStats | null;
}

// ============ Cost Models ============

export interface CostEstimate {
  operation: 'index' | 'search' | 'answer';
  embedding_tokens: number;
  embedding_cost: number;
  llm_tokens: number;
  llm_cost: number;
  total_cost: number;
}

export interface CostRecord {
  record_id: string;
  operation: string;
  repo_id: string;
  tokens: number;
  cost: number;
  timestamp: string;
}

export interface CostSummary {
  period: 'day' | 'week' | 'month';
  total_cost: number;
  by_operation: Record<string, number>;
  by_repo: Record<string, number>;
}
